branches:
  only:
  - master
env:
  global:
    - DOCKER_CLIENT_TIMEOUT="120"
    - COMPOSE_HTTP_TIMEOUT="120"
    - UID="2000"
services: 
- docker
push: &push
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - docker version
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - |
          for i in `docker images --format {{.Repository}}:{{.Tag}}`; do
            if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then 
              docker push $i;
            fi
          done
buster: &buster
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f dist/buster/docker-compose.yml build
        - docker rmi nginx:1.17.2
        - docker system prune -f
      <<: *push
jobs:
  include:
    - <<: *buster
      env:
      - LABEL: Buster
      - ANGULARCLI_VERSION: "7.1.4"
      - ANGULARBUILD_VERSION: "0.11.4"
